# Help Koreans help others! {#Improving fundraising culture in South Korea}

#### Keywords {-}

data science, fundraising, predictive modeling

## Direct mails and street fundraising are still popular in Korea!

Do direct mails and street fundraising sound like 90's? Surprisingly, they are still the leading fundraising channels in South Korea. Despite general perception that Korea is well advanced in technology, application of data in decision making is an overdue task for most corporates, especially for nonprofit organizations (NPO). Given the closed culture and language barriers, Koreans have developed Korean-only platforms and services rather than adapting U.S-based advanced platforms - Naver for Google, Kakaotalk for imessage/Whatsapp, and Jandi for Slack. Fundraising data platform is not an exception - HumanSoftware, which merely provides minimal dashboard, for Salesforce. Even though the size of nonprofit sector has rapidly grown in the past two decades, the sustainability of the organizations still relies on 90's tactics. This leads to 2 major problems in facilitating the development of nonprofit sector: 1) Despite of massive data collected on demographic donor information, critical information about donors' interests is still missing. 2) Accumulated donor information is not properly analyzed to better understand donors' behaviors, and thus not applied to optimize sustainable fundraising. "The key is moving from simply collecting data to actually leveraging nonprofit's data in the right ways," in order to bring fundraising practices of nonprofit sector to maturity. [@mclaughlin_using_2017]


## Engage with donors and predict how they'll react

Predictive modeling complemented with AB tests can help NPOs to solve such problems and optimize fundraising practices.
NPOs can start by segmenting donors into groups based on pre-collected demographic information, such as donor type, gender, age, income level, average gift size, number of gifts, number of years giving, and average donation amount. Then, AB tests can be run across multiple demographic dimensions on variables of marketing content and solicitation patterns. Marketing content variables range from fundraising topics, tone of voice, to designs donation buttons on emails, and solicitation pattern variables include fundraising channels, number of asks, and types of asks. From these tests, NPOs can learn about what donors engage with. One key point is that donors' behaviors and interests constantly change, and thus should AB tests. As a result of evolving AB tests, donors can be re-segmented by grouping based on what they engage with, rather than mere demographic information.

Now that NPOs better understand donors' motivations, they can predict the most effective ways to communicate with newly segmented groups. For example, traditional fundraising tactics might still work best with the older age groups, while digitalization might be critical for targeting younger groups by activating social media channels and utilizing email solicitation. For donors who are particularly enthusiastic about emergency fundraising, NPOs can send urgent asks with frequent situation updates. By applying personalized marketing with predictive models, NPOs can dramatically increase the giving amount and retain donors for a longer period of time.

Beyond marketing content, another advantage of predictive models is to identify loyal donors - who will give more often, larger amount, for a longer period of time. Predicting who is willing to give more in amount and frequency, NPOs can really target and ask these donors to upgrade in donation amount, convert to a regular donor, or give a larger amount for emergency cases like natural disasters. By targeting the right donors to engage further, NPOs can efficiently allocate budget in cultivating donors with higher lifetime value and fully optimize fundraising opportunities.

In addition, predictive models can be the most effective in planned donation, such as legacy or major donation, which is a form of donation prevalent in the most matured community, because it requires the deepest engagement with donors. By opening up the chances of cultivating planned givers, Korea will be one step closer to becoming a mature country in giving culture.


## The Art of Data Science

Predictive models will enable NPOs in Korea to constantly adapt marketing tools and solicitation methods for the right target groups, and engage more deeply with donors. This will result in not only higher retention rates and lifetime values, but also opportunities for planned donation. Since "donor retention … [is] the key to creating a sustainable financial foundation for nonprofit," NPOs will be able to optimize sustainable fundraising practices, equipped with evolving datasets and models. [@foran_donor_2017]
On a short-term note, collecting meaningful datasets and analyzing them will be time consuming and costly. Given the society's familiarity with traditional fundraising, abrupt changes might lead to temporary lag in fundraising. Advanced analytical tools from U.S. and European market will not be adapted to Korean market overnight. However, I think such difficulties are necessary growing pains in promoting the sustainable growth of nonprofit sector in Korea.
However, in applying data science, NPOs should remember that the primary goal is to engage with the donors more deeply. They should not be too focused on the science and get carried away from emotional engagement! "Nonprofit organizations need to balance the art and science of their efforts to accelerate performance and change." [@mclaughlin_balancing_2017]
