# People-saving algorithms {#Stop-the-killing}

#### Keywords {-}

Data Science, machine learning, algorithm, prevent, suicide, South Korea

 
 
## Suicide: A Bigger Threat than North Korea
 
According to the OECD Health Statistics 2015, an average of 29.1 people per 100,000 committed suicide in 2012 in South Korea, which is about 2 1/2 times the OECD average of 11.9. It is the highest suicidal rate among OECD countries, especially for teenagers and elders of age more than 60. [@OECD] Suicide is the No.1 cause of death among Koreans aged 10 to 39. Even without North Korea's threat, South Korea has enough killings on their own.


Despite the severity of high and increasing trends, countermeasures by the government have been inefficient. For instance, the handrails on Mapo bridge, where many suicides were reported, have been equipped with motion sensors to sense movements for suicide, lighting up with short phrases and showing photos of happy families among other things. However, suicide rates on Mapo bridge has actually increased after the sensors were implemented, and now it's even called "the suicide bridge." Fundamental reason of such happening is government's lack of understanding the nature of suicidal individuals, and therefore, what support such individuals need. In their defense, the difficulty of understanding motives of depressed citizens is because of social stigma against people who visit psychiatrists or therapists, making them "crazy people." Therefore, the existing Suicide Prevention Center stands for the sake of existence without actual visitors. Instead of approaching this problem prematurely, Korean government needs to take the right measure.

Machine learning algorithm will help Korean government to solve this social problem by associating behavioral patterns with suicidal risks and by detecting individuals at risk. 
 

## Machine Learning for Saving Lives

Machine Learning Algorithm can first collect training data on citizens' smartphone behaviors in order to correlate smartphone behaviors with symptoms of depression and use these findings to predict and identify individuals at risk of suicides. As a result, Korean government can intervene with depressed individuals' life before they make dangerous decisions.

First task is to collect meaningful training dataset of depressed citizens' behaviors on smartphones and feed them into the algorithm to correlate them with suicidal thoughts. What makes this task remarkably accessible is the application Kakaotalk, the single most-used messenger/SNS platform for Koreans: 43 out of 51 million Koreans are active users (84% penetration). [@Ecomaster] This application also provides other tools, such as audio/video calls, shopping platform (with KakaoPay), news browsing platform, search engine, and banking services - It is Facebook + Google + Amazon of Korea.
Suicide Prevention Center can open a private hotline on Kakaotalk application, so that citizens can reach out for help without risking revelation of their identification other than phone numbers. From individuals who reached out to hotline and agreed to share data, we can collect their behavioral data of chats, public posts, purchase patterns, engine searching patterns, and vocal cues on calls as a training dataset, and feed them into our machine learning algorithms. Diverse tools can be utilized to collect meaningful data, including natural language processing for private chats and keyword search patterns and image/text mining for public posts.

Once enough training data has been accumulated, machine learning algorithm can find consistent patterns among depressed users that are distinct from regular smartphone behaviors of general public to correlate them with suicidal thoughts. For an example, the algorithm might learn from dataset that "people who are contemplating ending their lives rarely use the word 'suicide'; words like 'ibuprofen' or 'bridge' are better indicators of suicidal thoughts." [@reardon_ai_2017] Or the data might show that depressed individuals exhibit impulsive behaviors in shopping or posting anonymous public messages on others' posts. Since there are resources of diverse angles available, from chatting to searching and purchasing, there might also be concurrent behaviors that together show strong evidences of emotional discomfort. Such findings can be defined as triggers to flag suicidal actions, when run against larger datasets.

Finally, now that smartphone behaviors associated with suicidal risks have been defined, algorithm can be run on the entire dataset of Kakaotalk users to detect which individuals show symptoms of depression or signs of suicidal attempts and predict the degree of risks. After detection, algorithm can automatically notify Suicide Prevention Center to approach such citizens at emotional risks, based on the severity of their status. Intervention can be conducted in many forms, such as exposing them with heart-warming quotes as a form of online ad, or even with Suicide Prevention Center hotline advertisements. Most effective methods and their results would also have to be constantly fed into the algorithms to determine and strengthen promising measures to save lives. Repetition of identifying depressed people and taking action will continuously generate data stream to be fed back into the algorithm to improve efficiency.
By intervening at an earlier stage before people develop extreme thoughts to end their own lives, Suicide Prevention Center can actually prevent suicides and provide appropriate help them to regain strength to carry on.


## Do They Want to be Detected?

Even though the potential of saving citizens at suicidal risks, there are downfalls of this machine learning algorithm. First, utilizing "passive" data in pursuit of detecting depressed individuals can be invading privacy of people, because they never agreed on sharing contents of private chats or smartphone behaviors to diagnose for depression specifically. Primary solution is to send out push notifications to all users for a new consent form, but this can also end up being a formality. Another option is to allow users to opt out from being screened for detection of depression.

In addition, point of intervention can also be controversial, since the users never agreed with interventions as well. Abrupt intervention might backfire and push them even further away from opening up to receiving help or affect them even more negatively by coercing unwanted revelation of their emotional status to a stranger. This risk might be reduced by strengthening the algorithm on effects of intervention after measures are taken. The more data is accumulated and studied, the more negative impact of intervention will be reduced.

Despite potential downside mentioned above, if implemented properly without causing users' resentment, this machine learning algorithm will effectively prevent potential suicides, especially considering the social context of South Korean culture where mental illness is stigmatized. Private approach without revelation of identification could reduce suicidal rate significantly.
Moreover, if data is collected continuously, the algorithm will also be able to find fundamental reasons behind people's suicides, some of which might be related to social structure of Korea. From the fact that suicide rates are higher in teenage groups and elderly, it's apparent that social welfare is not well established for weak social groups. By understanding specific and accurate reasons of difficulties for weak groups, Korean government can take measures to make fundamental adjustment in social systems to better citizens' lives.